name: Deploy
on:
  push: 
    branches: [ "main" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
#ssh username@ip 설정 파일
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        script: |
          cd ci-server
          git pull
          sh gradlew bulid
          nohup java -jar bulid/libs/*T.jar > /dev/null 2>&1 &
